# Generated by Django 4.2.16 on 2024-12-15 10:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0005_order_payment_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('transaction_id', models.TextField()),
                ('transaction_response', models.JSONField(null=True)),
                ('transaction_status', models.CharField(choices=[('INITIATE', 'Initiate'), ('COMPLETE', 'Complete'), ('FAIL', 'Fail')], max_length=20)),
                ('transaction_type', models.CharField(choices=[('ESEWA', 'Esewa'), ('KHALTI', 'Khalti')], max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_payment_histories', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='product.order')),
            ],
        ),
    ]
