# Generated by Django 4.2.16 on 2025-02-01 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_paymenthistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_auction_product',
            field=models.BooleanField(default=False, help_text='Check if this product is for auction.'),
        ),
    ]
