# Generated by Django 4.2.16 on 2025-02-02 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_product_is_auction_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='is_auctioned',
            field=models.BooleanField(default=False),
        ),
    ]
